# 数据源配置
dynamicds:
    orgCodeHeader: orgCode                            #orgCode HTTP header name
    tenants:                                          #具体机构的数据源配置
        master:
            url: jdbc:mysql://172.28.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
            driver: com.mysql.cj.jdbc.Driver
            userName: root
            password: 123456

        #dm:
        #    url: jdbc:dm://192.168.188.3:5236
        #    driver: dm.jdbc.driver.DmDriver
        #    userName: SYSDBA
        #    password: SYSDBA
    general:
        defaultTenant : master                   #默认数据源，可设置为一个空的database，仅供Spring cloud检查数据源的可连接性
            # 初始连接数
        initialSize: 5
            # 最小连接池数量
        minIdle: 6
            # 最大连接池数量
        maxActive: 20
            # 配置获取连接等待超时的时间
        maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        webStatFilter:
            enabled: true
        statViewServlet:
            enabled: true
                # 设置白名单，不填则允许所有访问
            allow:
            url-pattern: /druid/*
                # 控制台管理用户名和密码
            login-username:
            login-password:
        filter:
            stat:
                enabled: true
                    # 慢SQL记录
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: true
            wall:
                config:
                    multi-statement-allow: true
